const indonesianKecamatan = [
  {
    alamat: "Jl. Gatot Subroto No. 10",
    desa: "Bendul Merisi",
    kecamatan: "Sukun",
    kabupaten: "Kota Malang",
    provinsi: "Jawa Timur",
  },
  {
    alamat: "Jl. Ahmad Yani No. 25",
    desa: "Ngaglik",
    kecamatan: "Sleman",
    kabupaten: "Kabupaten Sleman",
    provinsi: "Daerah Istimewa Yogyakarta",
  },
  {
    alamat: "Jl. Sudirman No. 8",
    desa: "Kebon Jeruk",
    kecamatan: "Kebon Jeruk",
    kabupaten: "Jakarta Barat",
    provinsi: "DKI Jakarta",
  },
  {
    alamat: "Jl. Diponegoro No. 15",
    desa: "Karangkajen",
    kecamatan: "Karangkajen",
    kabupaten: "Kabupaten Sleman",
    provinsi: "Daerah Istimewa Yogyakarta",
  },
  {
    alamat: "Jl. Pemuda No. 30",
    desa: "Bintara",
    kecamatan: "Bekasi Timur",
    kabupaten: "Kota Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    alamat: "Jl. Imam Bonjol No. 15",
    desa: "Dago",
    kecamatan: "Coblong",
    kabupaten: "Kota Bandung",
    provinsi: "Jawa Barat",
  },
  {
    alamat: "Jl. Raya Cilandak KKO No. 25",
    desa: "Cilandak Timur",
    kecamatan: "Cilandak",
    kabupaten: "Jakarta Selatan",
    provinsi: "DKI Jakarta",
  },
  {
    alamat: "Jl. Pahlawan No. 8",
    desa: "Banyumanik",
    kecamatan: "Banyumanik",
    kabupaten: "Kota Semarang",
    provinsi: "Jawa Tengah",
  },
  {
    alamat: "Jl. Dr. Wahidin Sudirohusodo No. 10",
    desa: "Karangrejo",
    kecamatan: "Tegalrejo",
    kabupaten: "Kota Yogyakarta",
    provinsi: "Daerah Istimewa Yogyakarta",
  },
  {
    alamat: "Jl. Diponegoro No. 50",
    desa: "Tanjung Mas",
    kecamatan: "Pontianak Kota",
    kabupaten: "Kota Pontianak",
    provinsi: "Kalimantan Barat",
  },
  {
    alamat: "Jl. Gatot Subroto No. 10",
    desa: "Bendul Merisi",
    kecamatan: "Sukun",
    kabupaten: "Kota Malang",
    provinsi: "Jawa Timur",
  },
  {
    alamat: "Jl. Ahmad Yani No. 25",
    desa: "Ngaglik",
    kecamatan: "Sleman",
    kabupaten: "Kabupaten Sleman",
    provinsi: "Daerah Istimewa Yogyakarta",
  },
  {
    alamat: "Jl. Sudirman No. 8",
    desa: "Kebon Jeruk",
    kecamatan: "Kebon Jeruk",
    kabupaten: "Jakarta Barat",
    provinsi: "DKI Jakarta",
  },
  {
    alamat: "Jl. Diponegoro No. 15",
    desa: "Karangkajen",
    kecamatan: "Karangkajen",
    kabupaten: "Kabupaten Sleman",
    provinsi: "Daerah Istimewa Yogyakarta",
  },
  {
    alamat: "Jl. Pemuda No. 30",
    desa: "Bintara",
    kecamatan: "Bekasi Timur",
    kabupaten: "Kota Bekasi",
    provinsi: "Jawa Barat",
  },
  {
    alamat: "Jl. Sudirman No. 12",
    desa: "Setiabudi",
    kecamatan: "Setiabudi",
    kabupaten: "Jakarta Selatan",
    provinsi: "DKI Jakarta",
  },
  {
    alamat: "Jl. Raya Bogor No. 25",
    desa: "Ciracas",
    kecamatan: "Ciracas",
    kabupaten: "Jakarta Timur",
    provinsi: "DKI Jakarta",
  },
  {
    alamat: "Jl. Gatot Subroto No. 7",
    desa: "Pandeyan",
    kecamatan: "Umbulharjo",
    kabupaten: "Kota Yogyakarta",
    provinsi: "Daerah Istimewa Yogyakarta",
  },
  {
    alamat: "Jl. Raya Waru No. 18",
    desa: "Waru",
    kecamatan: "Sidoarjo",
    kabupaten: "Kabupaten Sidoarjo",
    provinsi: "Jawa Timur",
  },
  {
    alamat: "Jl. Supratman No. 30",
    desa: "Kemayoran",
    kecamatan: "Kemayoran",
    kabupaten: "Jakarta Pusat",
    provinsi: "DKI Jakarta",
  },
  {
    alamat: "Jl. Majapahit No. 5",
    desa: "Pacarkembang",
    kecamatan: "Pacarkembang",
    kabupaten: "Surabaya",
    provinsi: "Jawa Timur",
  },
  {
    alamat: "Jl. Pangeran Antasari No. 12",
    desa: "Cipedes",
    kecamatan: "Sukajadi",
    kabupaten: "Kota Bandung",
    provinsi: "Jawa Barat",
  },
  {
    alamat: "Jl. Jendral Sudirman No. 20",
    desa: "Sukun",
    kecamatan: "Sukun",
    kabupaten: "Kota Malang",
    provinsi: "Jawa Timur",
  },
  {
    alamat: "Jl. Dipenegoro No. 35",
    desa: "Ngemplak",
    kecamatan: "Ngemplak",
    kabupaten: "Kabupaten Sleman",
    provinsi: "Daerah Istimewa Yogyakarta",
  },
];

module.exports = indonesianKecamatan;
