const mongoose = require("mongoose");

const searchSuggestSchema = new mongoose.Schema({
  suggest: {
    type: String,
  },
  jmlDicari: {
    type: Number,
  },
});

const searchSuggest = mongoose.model("searchSuggest", searchSuggestSchema);

module.exports = searchSuggest;

const dummyData = [
  { suggest: "Kucing", jmlDicari: 100 },
  { suggest: "Anjing", jmlDicari: 80 },
  { suggest: "Bunga", jmlDicari: 70 },
  { suggest: "Makanan", jmlDicari: 65 },
  { suggest: "Mobil", jmlDicari: 60 },
  { suggest: "Pakaian", jmlDicari: 55 },
  { suggest: "Sepeda", jmlDicari: 50 },
  { suggest: "Kopi", jmlDicari: 45 },
  { suggest: "Tiket", jmlDicari: 40 },
  { suggest: "Hotel", jmlDicari: 35 },
  { suggest: "Musik", jmlDicari: 30 },
  { suggest: "Film", jmlDicari: 25 },
  { suggest: "Buku", jmlDicari: 20 },
  { suggest: "Olahraga", jmlDicari: 15 },
  { suggest: "Game", jmlDicari: 10 },
  { suggest: "Komputer", jmlDicari: 5 },
  { suggest: "Ponsel", jmlDicari: 5 },
  { suggest: "Rumah", jmlDicari: 4 },
  { suggest: "Pendidikan", jmlDicari: 4 },
  { suggest: "Wisata", jmlDicari: 3 },
  { suggest: "Kesehatan", jmlDicari: 3 },
  { suggest: "Liburan", jmlDicari: 3 },
  { suggest: "Photography", jmlDicari: 3 },
  { suggest: "Pertanian", jmlDicari: 2 },
  { suggest: "Kuliner", jmlDicari: 2 },
  { suggest: "Seni", jmlDicari: 2 },
  { suggest: "Desain", jmlDicari: 2 },
  { suggest: "Fotografi", jmlDicari: 2 },
  { suggest: "Teknologi", jmlDicari: 2 },
  { suggest: "Hobi", jmlDicari: 2 },
  { suggest: "Pertunjukan", jmlDicari: 1 },
  { suggest: "Konser", jmlDicari: 1 },
  { suggest: "Fashion", jmlDicari: 1 },
  { suggest: "Kesehatan Mental", jmlDicari: 1 },
  { suggest: "Berkebun", jmlDicari: 1 },
  { suggest: "Ruang Tamu", jmlDicari: 1 },
  { suggest: "Kamar Tidur", jmlDicari: 1 },
  { suggest: "Dekorasi", jmlDicari: 1 },
  { suggest: "Kendaraan Listrik", jmlDicari: 1 },
  { suggest: "Gadget", jmlDicari: 1 },
  { suggest: "Kesehatan Gigi", jmlDicari: 1 },
  { suggest: "Rumah Tangga", jmlDicari: 1 },
  { suggest: "Kecantikan", jmlDicari: 1 },
  { suggest: "Elektronik", jmlDicari: 1 },
  { suggest: "Alam", jmlDicari: 1 },
  { suggest: "Museum", jmlDicari: 1 },
  { suggest: "Wisata Kuliner", jmlDicari: 1 },
  { suggest: "Meme", jmlDicari: 1 },
  { suggest: "Humor", jmlDicari: 1 },
  { suggest: "Motivasi", jmlDicari: 1 },
  { suggest: "Inspirasi", jmlDicari: 1 },
  { suggest: "Cerita", jmlDicari: 1 },
  { suggest: "Cinta", jmlDicari: 1 },
  { suggest: "Sosial", jmlDicari: 1 },
  // Lanjutkan dengan data dummy lainnya sesuai kebutuhan
  { suggest: "Gaya Hidup", jmlDicari: 1 },
  { suggest: "Kesehatan Tubuh", jmlDicari: 1 },
  { suggest: "Bisnis", jmlDicari: 1 },
  { suggest: "Startup", jmlDicari: 1 },
  { suggest: "Keuangan", jmlDicari: 1 },
  { suggest: "Investasi", jmlDicari: 1 },
  { suggest: "Pendidikan Anak", jmlDicari: 1 },
  { suggest: "Parenting", jmlDicari: 1 },
  { suggest: "Otomotif", jmlDicari: 1 },
  { suggest: "Teknologi Wearable", jmlDicari: 1 },
  { suggest: "Seni Visual", jmlDicari: 1 },
  { suggest: "Desain Interior", jmlDicari: 1 },
  { suggest: "Desain Eksterior", jmlDicari: 1 },
  { suggest: "Hiburan", jmlDicari: 1 },
  { suggest: "Kecantikan Kulit", jmlDicari: 1 },
  { suggest: "Kesehatan Wanita", jmlDicari: 1 },
  { suggest: "Kesehatan Pria", jmlDicari: 1 },
  { suggest: "Kesehatan Anak", jmlDicari: 1 },
  { suggest: "Kesehatan Umum", jmlDicari: 1 },
  { suggest: "Makanan Sehat", jmlDicari: 1 },
  { suggest: "Laptop Toshiba", jmlDicari: 5 },
  { suggest: "Smartphone terbaru", jmlDicari: 3 },
  { suggest: "Headphones estetik", jmlDicari: 8 },
  { suggest: "Camera", jmlDicari: 2 },
  { suggest: "Smartwatch", jmlDicari: 6 },
  { suggest: "Keyboard", jmlDicari: 1 },
  { suggest: "Mouse", jmlDicari: 4 },
  { suggest: "Monitor", jmlDicari: 7 },
  { suggest: "Printer", jmlDicari: 3 },
  { suggest: "Tablet", jmlDicari: 5 },
  { suggest: "Router", jmlDicari: 21 },
  { suggest: "Speaker", jmlDicari: 21 },
  { suggest: "Microphone", jmlDicari: 21 },
  { suggest: "Webcam", jmlDicari: 21 },
  { suggest: "Charger", jmlDicari: 21 },
  { suggest: "Laptop", jmlDicari: 21 },
  { suggest: "Smartphone", jmlDicari: 21 },
  { suggest: "Headphones", jmlDicari: 21 },
  { suggest: "Hard Drive", jmlDicari: 21 },
  { suggest: "SSD", jmlDicari: 21 },
  { suggest: "RAM", jmlDicari: 21 },
  { suggest: "Graphics Card", jmlDicari: 21 },
  { suggest: "Motherboard", jmlDicari: 21 },
  { suggest: "CPU", jmlDicari: 21 },
  { suggest: "Power Supply", jmlDicari: 21 },
  { suggest: "Case", jmlDicari: 21 },
  { suggest: "Cooling Fan", jmlDicari: 21 },
  { suggest: "Projector", jmlDicari: 21 },
  { suggest: "VR Headset", jmlDicari: 21 },
  { suggest: "E-reader", jmlDicari: 21 },
  { suggest: "Game Console", jmlDicari: 21 },
  { suggest: "Fitness Tracker", jmlDicari: 21 },
  { suggest: "Portable Speaker", jmlDicari: 21 },
  { suggest: "Drone", jmlDicari: 21 },
  { suggest: "Action Camera", jmlDicari: 21 },
  { suggest: "Electric Scooter", jmlDicari: 21 },
  { suggest: "Smart Light", jmlDicari: 21 },
  { suggest: "Smart Thermostat", jmlDicari: 21 },
  { suggest: "Bluetooth Headset", jmlDicari: 21 },
  { suggest: "Wireless Charger", jmlDicari: 21 },
  { suggest: "Portable Charger", jmlDicari: 21 },
  { suggest: "Digital Camera", jmlDicari: 21 },
  { suggest: "Laptop Gaming", jmlDicari: 21 },
  { suggest: "Gaming Mouse", jmlDicari: 21 },
  { suggest: "Mechanical Keyboard", jmlDicari: 21 },
  { suggest: "Smart TV", jmlDicari: 21 },
  { suggest: "LED Monitor", jmlDicari: 21 },
  { suggest: "External SSD", jmlDicari: 21 },
  { suggest: "Portable Hard Drive", jmlDicari: 21 },
  { suggest: "USB Flash Drive", jmlDicari: 21 },
  { suggest: "Memory Card", jmlDicari: 21 },
  { suggest: "Wireless Router", jmlDicari: 21 },
  { suggest: "Noise Cancelling Headphones", jmlDicari: 21 },
  { suggest: "Smart Home Hub", jmlDicari: 21 },
  { suggest: "Smart Door Lock", jmlDicari: 21 },
  { suggest: "Smart Security Camera", jmlDicari: 21 },
  { suggest: "Smart Doorbell", jmlDicari: 21 },
  { suggest: "Robot Vacuum", jmlDicari: 21 },
  { suggest: "Electric Bike", jmlDicari: 21 },
  { suggest: "Smart Oven", jmlDicari: 21 },
  { suggest: "Smart Fridge", jmlDicari: 21 },
  { suggest: "Smart Washer", jmlDicari: 21 },
  { suggest: "Smart Dryer", jmlDicari: 21 },
  { suggest: "Wireless Earbuds", jmlDicari: 21 },
  { suggest: "Bluetooth Speaker", jmlDicari: 21 },
  { suggest: "Portable Projector", jmlDicari: 21 },
  { suggest: "Streaming Device", jmlDicari: 21 },
  { suggest: "Smart Coffee Maker", jmlDicari: 21 },
  { suggest: "Electric Toothbrush", jmlDicari: 21 },
  { suggest: "Smart Mirror", jmlDicari: 21 },
  { suggest: "Smart Scale", jmlDicari: 21 },
  { suggest: "Fitness Band", jmlDicari: 21 },
  { suggest: "Smart Jump Rope", jmlDicari: 21 },
  { suggest: "Smart Water Bottle", jmlDicari: 21 },
  { suggest: "Smart Ring", jmlDicari: 21 },
  { suggest: "VR Controller", jmlDicari: 21 },
  { suggest: "Smart Switch", jmlDicari: 21 },
  { suggest: "Smart Plug", jmlDicari: 21 },
  { suggest: "Smart Bulb", jmlDicari: 21 },
  { suggest: "Smart Thermometer", jmlDicari: 21 },
  { suggest: "Air Purifier", jmlDicari: 21 },
  { suggest: "Smart Fan", jmlDicari: 21 },
  { suggest: "Smart Heater", jmlDicari: 21 },
  { suggest: "Electric Fireplace", jmlDicari: 21 },
  { suggest: "Portable AC", jmlDicari: 21 },
  { suggest: "Smart Diffuser", jmlDicari: 21 },
  { suggest: "Smart Alarm Clock", jmlDicari: 21 },
  { suggest: "Wireless Charging Pad", jmlDicari: 21 },
  { suggest: "Bluetooth Adapter", jmlDicari: 21 },
  { suggest: "Smart Glasses", jmlDicari: 21 },
  { suggest: "Smart Notebook", jmlDicari: 21 },
  { suggest: "3D Printer", jmlDicari: 21 },
  { suggest: "Smart Pen", jmlDicari: 21 },
  { suggest: "Wireless Keyboard", jmlDicari: 21 },
  { suggest: "Wireless Mouse", jmlDicari: 21 },
  { suggest: "Docking Station", jmlDicari: 21 },
  { suggest: "Laptop Stand", jmlDicari: 21 },
  { suggest: "Gaming Chair", jmlDicari: 21 },
  { suggest: "Ergonomic Keyboard", jmlDicari: 21 },
  { suggest: "Ergonomic Mouse", jmlDicari: 21 },
  { suggest: "Monitor Stand", jmlDicari: 21 },
  { suggest: "Cable Organizer", jmlDicari: 21 },
  { suggest: "Screen Protector", jmlDicari: 21 },
  { suggest: "Laptop Bag", jmlDicari: 21 },
  { suggest: "Laptop Cooling Pad", jmlDicari: 21 },
  { suggest: "Laptop Charger", jmlDicari: 21 },
  { suggest: "USB Hub", jmlDicari: 21 },
  { suggest: "Webcam Cover", jmlDicari: 21 },
  { suggest: "Privacy Screen", jmlDicari: 21 },
  { suggest: "Mouse Pad", jmlDicari: 21 },
  { suggest: "Wrist Rest", jmlDicari: 21 },
  { suggest: "Desk Lamp", jmlDicari: 21 },
  { suggest: "Surge Protector", jmlDicari: 21 },
  { suggest: "UPS Battery Backup", jmlDicari: 21 },
  { suggest: "Ethernet Cable", jmlDicari: 21 },
  { suggest: "HDMI Cable", jmlDicari: 21 },
  { suggest: "VGA Cable", jmlDicari: 21 },
  { suggest: "Gaming Monitor", jmlDicari: 21 },
  { suggest: "4K TV", jmlDicari: 21 },
  { suggest: "Smart Projector", jmlDicari: 21 },
  { suggest: "Wireless Headphones", jmlDicari: 21 },
  { suggest: "Noise Cancelling Earbuds", jmlDicari: 21 },
  { suggest: "Smart Home Camera", jmlDicari: 21 },
  { suggest: "Smart Lock", jmlDicari: 21 },
  { suggest: "Smart Light Switch", jmlDicari: 21 },
  { suggest: "Smart Thermostat", jmlDicari: 21 },
  { suggest: "Smart Plug", jmlDicari: 21 },
  { suggest: "Smart Dimmer", jmlDicari: 21 },
  { suggest: "Smart Garage Door Opener", jmlDicari: 21 },
  { suggest: "WiFi Extender", jmlDicari: 21 },
  { suggest: "Mesh WiFi System", jmlDicari: 21 },
  { suggest: "Smart Smoke Detector", jmlDicari: 21 },
  { suggest: "Smart Carbon Monoxide Detector", jmlDicari: 21 },
  { suggest: "Smart Water Leak Detector", jmlDicari: 21 },
  { suggest: "Smart Baby Monitor", jmlDicari: 21 },
  { suggest: "Smart Pet Feeder", jmlDicari: 21 },
  { suggest: "Smart Pet Camera", jmlDicari: 21 },
  { suggest: "Portable Power Station", jmlDicari: 21 },
  { suggest: "Solar Charger", jmlDicari: 21 },
  { suggest: "Electric Skateboard", jmlDicari: 21 },
  { suggest: "Electric Unicycle", jmlDicari: 21 },
  { suggest: "Hoverboard", jmlDicari: 21 },
  { suggest: "Smart Helmet", jmlDicari: 21 },
  { suggest: "Smart Bike Lock", jmlDicari: 21 },
  { suggest: "Smart Bike Light", jmlDicari: 21 },
  { suggest: "Smart Doorbell Camera", jmlDicari: 21 },
  { suggest: "Smart Outdoor Camera", jmlDicari: 21 },
  { suggest: "Smart Floodlight Camera", jmlDicari: 21 },
  { suggest: "Smart Video Doorbell", jmlDicari: 21 },
  { suggest: "Smart Indoor Camera", jmlDicari: 21 },
  { suggest: "Smart Security System", jmlDicari: 21 },
  { suggest: "Smart Alarm System", jmlDicari: 21 },
  { suggest: "Smart Panic Button", jmlDicari: 21 },
  { suggest: "Smart Motion Sensor", jmlDicari: 21 },
  { suggest: "Smart Contact Sensor", jmlDicari: 21 },
  { suggest: "Smart Glass Break Sensor", jmlDicari: 21 },
  { suggest: "Smart Temperature Sensor", jmlDicari: 21 },
  { suggest: "Smart Humidity Sensor", jmlDicari: 21 },
  { suggest: "Smart Air Quality Monitor", jmlDicari: 21 },
  { suggest: "Smart Light Bulb", jmlDicari: 21 },
  { suggest: "Smart LED Strip", jmlDicari: 21 },
  { suggest: "Smart Color Bulb", jmlDicari: 21 },
  { suggest: "Smart Light Panel", jmlDicari: 21 },
  { suggest: "Smart Light Strip", jmlDicari: 21 },
  { suggest: "Smart Light Kit", jmlDicari: 21 },
  { suggest: "Smart Ceiling Light", jmlDicari: 21 },
  { suggest: "Smart Wall Light", jmlDicari: 21 },
  { suggest: "Smart Desk Lamp", jmlDicari: 21 },
  { suggest: "Smart Floor Lamp", jmlDicari: 21 },
  { suggest: "Smart Table Lamp", jmlDicari: 21 },
  { suggest: "Smart Pendant Light", jmlDicari: 21 },
  { suggest: "Smart Garden Light", jmlDicari: 21 },
  { suggest: "Smart Path Light", jmlDicari: 21 },
  { suggest: "Smart Floodlight", jmlDicari: 21 },
  { suggest: "Smart String Light", jmlDicari: 21 },
  { suggest: "Smart Festoon Light", jmlDicari: 21 },
  { suggest: "Smart Rope Light", jmlDicari: 21 },
  { suggest: "Smart Chandelier", jmlDicari: 21 },
  { suggest: "Smart Ceiling Fan", jmlDicari: 21 },
  { suggest: "Smart Fan", jmlDicari: 21 },
  { suggest: "Smart Heater", jmlDicari: 21 },
  { suggest: "Smart Radiator", jmlDicari: 21 },
  { suggest: "Smart Thermostat Valve", jmlDicari: 21 },
  { suggest: "Smart Thermostat Controller", jmlDicari: 21 },
  { suggest: "Smart Boiler Controller", jmlDicari: 21 },
  { suggest: "Smart Hot Water Controller", jmlDicari: 21 },
  { suggest: "Smart Irrigation Controller", jmlDicari: 21 },
  { suggest: "Smart Sprinkler Controller", jmlDicari: 21 },
  { suggest: "Smart Pool Controller", jmlDicari: 21 },
  { suggest: "Smart Spa Controller", jmlDicari: 21 },
  { suggest: "Smart Sauna Controller", jmlDicari: 21 },
  { suggest: "Smart Hot Tub Controller", jmlDicari: 21 },
  { suggest: "Smart Shower Controller", jmlDicari: 21 },
  { suggest: "Smart Bathtub Controller", jmlDicari: 21 },
  { suggest: "Smart Toilet Controller", jmlDicari: 21 },
  { suggest: "Smart Bidet Controller", jmlDicari: 21 },
  { suggest: "Smart Washer Controller", jmlDicari: 21 },
  { suggest: "Smart Dryer Controller", jmlDicari: 21 },
  { suggest: "Smart Dishwasher Controller", jmlDicari: 21 },
  { suggest: "Smart Refrigerator Controller", jmlDicari: 21 },
  { suggest: "Smart Freezer Controller", jmlDicari: 21 },
  { suggest: "Smart Oven Controller", jmlDicari: 21 },
  { suggest: "Smart Microwave Controller", jmlDicari: 21 },
  { suggest: "Smart Cooktop Controller", jmlDicari: 21 },
  { suggest: "Smart Range Hood Controller", jmlDicari: 21 },
  { suggest: "Smart Coffee Maker Controller", jmlDicari: 21 },
  { suggest: "Smart Kettle Controller", jmlDicari: 21 },
  { suggest: "Smart Toaster Controller", jmlDicari: 21 },
  { suggest: "Smart Blender Controller", jmlDicari: 21 },
  { suggest: "Smart Mixer Controller", jmlDicari: 21 },
  { suggest: "Smart Juicer Controller", jmlDicari: 21 },
  { suggest: "Smart Food Processor Controller", jmlDicari: 21 },
  { suggest: "Smart Air Fryer Controller", jmlDicari: 21 },
  { suggest: "Smart Slow Cooker Controller", jmlDicari: 21 },
  { suggest: "Smart Pressure Cooker Controller", jmlDicari: 21 },
  { suggest: "Smart Rice Cooker Controller", jmlDicari: 21 },
  { suggest: "Smart Rice Cooker", jmlDicari: 21 },
  { suggest: "Smart Bread Maker", jmlDicari: 21 },
  { suggest: "Smart Ice Cream Maker", jmlDicari: 21 },
  { suggest: "Smart Popcorn Maker", jmlDicari: 21 },
  { suggest: "Smart Soda Maker", jmlDicari: 21 },
  { suggest: "Smart Wine Opener", jmlDicari: 21 },
  { suggest: "Smart Wine Preserver", jmlDicari: 21 },
  { suggest: "Smart Wine Cooler", jmlDicari: 21 },
  { suggest: "Smart Beer Dispenser", jmlDicari: 21 },
  { suggest: "Smart Cocktail Maker", jmlDicari: 21 },
  { suggest: "Smart Drink Mixer", jmlDicari: 21 },
  { suggest: "Smart Drink Warmer", jmlDicari: 21 },
  { suggest: "Smart Bottle Opener", jmlDicari: 21 },
  { suggest: "Smart Bottle Chiller", jmlDicari: 21 },
  { suggest: "Smart Bottle Warmer", jmlDicari: 21 },
  { suggest: "Smart Food Scale", jmlDicari: 21 },
  { suggest: "Smart Meat Thermometer", jmlDicari: 21 },
  { suggest: "Smart Cooking Pot", jmlDicari: 21 },
  { suggest: "Smart Grill", jmlDicari: 21 },
  { suggest: "Smart Smoker", jmlDicari: 21 },
  { suggest: "Smart Pizza Oven", jmlDicari: 21 },
  { suggest: "Smart Deep Fryer", jmlDicari: 21 },
  { suggest: "Smart Air Fryer", jmlDicari: 21 },
  { suggest: "Smart Waffle Maker", jmlDicari: 21 },
  { suggest: "Smart Pancake Maker", jmlDicari: 21 },
  { suggest: "Smart Crepe Maker", jmlDicari: 21 },
  { suggest: "Smart Egg Cooker", jmlDicari: 21 },
  { suggest: "Smart Toaster Oven", jmlDicari: 21 },
  { suggest: "Smart Convection Oven", jmlDicari: 21 },
  { suggest: "Smart Microwave Oven", jmlDicari: 21 },
  { suggest: "Smart Steamer", jmlDicari: 21 },
  { suggest: "Smart Blender", jmlDicari: 21 },
  { suggest: "Smart Food Processor", jmlDicari: 21 },
  { suggest: "Smart Hand Mixer", jmlDicari: 21 },
  { suggest: "Smart Stand Mixer", jmlDicari: 21 },
  { suggest: "Smart Juicer", jmlDicari: 21 },
  { suggest: "Smart Citrus Juicer", jmlDicari: 21 },
  { suggest: "Smart Cold Press Juicer", jmlDicari: 21 },
  { suggest: "Smart Centrifugal Juicer", jmlDicari: 21 },
  { suggest: "Smart Masticating Juicer", jmlDicari: 21 },
  { suggest: "Smart Spiralizer", jmlDicari: 21 },
  { suggest: "Smart Coffee Grinder", jmlDicari: 21 },
  { suggest: "Smart Burr Grinder", jmlDicari: 21 },
  { suggest: "Smart Drip Coffee Maker", jmlDicari: 21 },
  { suggest: "Smart Espresso Maker", jmlDicari: 21 },
  { suggest: "Smart French Press", jmlDicari: 21 },
  { suggest: "Smart Pour Over Coffee Maker", jmlDicari: 21 },
  { suggest: "Smart Single Serve Coffee Maker", jmlDicari: 21 },
  { suggest: "Smart Cold Brew Coffee Maker", jmlDicari: 21 },
  { suggest: "Smart Tea Maker", jmlDicari: 21 },
  { suggest: "Smart Electric Kettle", jmlDicari: 21 },
  { suggest: "Smart Tea Infuser", jmlDicari: 21 },
  { suggest: "Smart Tea Press", jmlDicari: 21 },
  { suggest: "Smart Tea Steeper", jmlDicari: 21 },
  { suggest: "Smart Tea Pot", jmlDicari: 21 },
  { suggest: "Smart Tea Brewer", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Squeezer", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Holder", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Organizer", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Dispenser", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Caddy", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Tray", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Bin", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Box", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Case", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Container", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Holder", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Organizer", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Dispenser", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Caddy", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Tray", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Bin", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Box", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Case", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Container", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Storage", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Keeper", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Saver", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Preserver", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Protector", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Squeezer", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Holder", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Organizer", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Dispenser", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Caddy", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Tray", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Bin", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Box", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Case", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Container", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Storage", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Keeper", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Saver", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Preserver", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Protector", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Squeezer", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Holder", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Organizer", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Dispenser", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Caddy", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Tray", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Bin", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Box", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Case", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Container", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Storage", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Keeper", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Saver", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Preserver", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Protector", jmlDicari: 21 },
  { suggest: "Smart Tea Bag Squeezer", jmlDicari: 21 },
  { suggest: "Smart Watering Can", jmlDicari: 21 },
  { suggest: "Smart Garden Hose", jmlDicari: 21 },
  { suggest: "Smart Lawn Mower", jmlDicari: 21 },
  { suggest: "Smart Weed Trimmer", jmlDicari: 21 },
  { suggest: "Smart Hedge Trimmer", jmlDicari: 21 },
  { suggest: "Smart Leaf Blower", jmlDicari: 21 },
  { suggest: "Smart Snow Blower", jmlDicari: 21 },
  { suggest: "Smart Pressure Washer", jmlDicari: 21 },
  { suggest: "Smart Power Washer", jmlDicari: 21 },
  { suggest: "Smart Power Tool", jmlDicari: 21 },
  { suggest: "Smart Drill", jmlDicari: 21 },
  { suggest: "Smart Saw", jmlDicari: 21 },
  { suggest: "Smart Sander", jmlDicari: 21 },
  { suggest: "Smart Grinder", jmlDicari: 21 },
  { suggest: "Smart Orbital Sander", jmlDicari: 21 },
  { suggest: "Smart Heat Gun", jmlDicari: 21 },
  { suggest: "Smart Hot Glue Gun", jmlDicari: 21 },
  { suggest: "Smart Caulking Gun", jmlDicari: 21 },
  { suggest: "Smart Putty Knife", jmlDicari: 21 },
  { suggest: "Smart Trowel", jmlDicari: 21 },
  { suggest: "Smart Hammer", jmlDicari: 21 },
  { suggest: "Smart Wrench", jmlDicari: 21 },
  { suggest: "Smart Pliers", jmlDicari: 21 },
  { suggest: "Smart Screwdriver", jmlDicari: 21 },
  { suggest: "Smart Utility Knife", jmlDicari: 21 },
  { suggest: "Smart Box Cutter", jmlDicari: 21 },
  { suggest: "Smart Tape Measure", jmlDicari: 21 },
  { suggest: "Smart Level", jmlDicari: 21 },
  { suggest: "Smart Stud Finder", jmlDicari: 21 },
  { suggest: "Smart Moisture Meter", jmlDicari: 21 },
  { suggest: "Smart Metal Detector", jmlDicari: 21 },
  { suggest: "Smart Thermal Camera", jmlDicari: 21 },
  { suggest: "Smart Endoscope Camera", jmlDicari: 21 },
  { suggest: "Smart Inspection Camera", jmlDicari: 21 },
  { suggest: "Smart Laser Measure", jmlDicari: 21 },
  { suggest: "Smart Laser Level", jmlDicari: 21 },
  { suggest: "Smart Laser Distance Meter", jmlDicari: 21 },
  { suggest: "Smart Laser Rangefinder", jmlDicari: 21 },
  { suggest: "Smart Infrared Thermometer", jmlDicari: 21 },
  { suggest: "Smart Multimeter", jmlDicari: 21 },
  { suggest: "Smart Clamp Meter", jmlDicari: 21 },
  { suggest: "Smart Voltage Tester", jmlDicari: 21 },
  { suggest: "Smart Circuit Tester", jmlDicari: 21 },
  { suggest: "Smart Electrical Tester", jmlDicari: 21 },
  { suggest: "Smart Outlet Tester", jmlDicari: 21 },
  { suggest: "Smart GFCI Tester", jmlDicari: 21 },
  { suggest: "Smart Wire Stripper", jmlDicari: 21 },
  { suggest: "Smart Wire Crimper", jmlDicari: 21 },
  { suggest: "Smart Wire Cutter", jmlDicari: 21 },
  { suggest: "Smart Soldering Iron", jmlDicari: 21 },
  { suggest: "Smart Hot Air Rework Station", jmlDicari: 21 },
  { suggest: "Smart 3D Printer", jmlDicari: 21 },
  { suggest: "Smart CNC Machine", jmlDicari: 21 },
  { suggest: "Smart Laser Engraver", jmlDicari: 21 },
  { suggest: "Smart Vinyl Cutter", jmlDicari: 21 },
  { suggest: "Smart Heat Press Machine", jmlDicari: 21 },
  { suggest: "Smart Embroidery Machine", jmlDicari: 21 },
  { suggest: "Smart Sewing Machine", jmlDicari: 21 },
  { suggest: "Smart Serger", jmlDicari: 21 },
  { suggest: "Smart Overlock Machine", jmlDicari: 21 },
  { suggest: "Smart Embroidery Software", jmlDicari: 21 },
  { suggest: "Smart Pattern Design Software", jmlDicari: 21 },
  { suggest: "Smart Quilting Software", jmlDicari: 21 },
  { suggest: "Smart Fabric Cutting Machine", jmlDicari: 21 },
  { suggest: "Smart Fabric Printer", jmlDicari: 21 },
  { suggest: "Smart Fabric Transfer Printer", jmlDicari: 21 },
  { suggest: "Smart Knitting Machine", jmlDicari: 21 },
  { suggest: "Smart Crochet Machine", jmlDicari: 21 },
  { suggest: "Smart Weaving Loom", jmlDicari: 21 },
  { suggest: "Smart Spinning Wheel", jmlDicari: 21 },
  { suggest: "Smart Yarn Winder", jmlDicari: 21 },
  { suggest: "Smart Yarn Ball Winder", jmlDicari: 21 },
  { suggest: "Smart Yarn Swift", jmlDicari: 21 },
  { suggest: "Smart Needle Felting Machine", jmlDicari: 21 },
  { suggest: "Smart Rug Tufting Gun", jmlDicari: 21 },
  { suggest: "Smart Leather Working Tools", jmlDicari: 21 },
  { suggest: "Smart Shoe Making Tools", jmlDicari: 21 },
  { suggest: "Smart Jewelry Making Tools", jmlDicari: 21 },
  { suggest: "Smart Beading Tools", jmlDicari: 21 },
  { suggest: "Smart Wire Wrapping Tools", jmlDicari: 21 },
  { suggest: "Smart Resin Casting Tools", jmlDicari: 21 },
  { suggest: "Smart Soap Making Tools", jmlDicari: 21 },
  { suggest: "Smart Candle Making Tools", jmlDicari: 21 },
  { suggest: "Smart Bath Bomb Making Tools", jmlDicari: 21 },
  { suggest: "Smart Pottery Wheel", jmlDicari: 21 },
  { suggest: "Smart Kiln", jmlDicari: 21 },
  { suggest: "Smart Glass Blowing Tools", jmlDicari: 21 },
  { suggest: "Smart Woodworking Tools", jmlDicari: 21 },
  { suggest: "Smart Wood Lathe", jmlDicari: 21 },
  { suggest: "Smart Scroll Saw", jmlDicari: 21 },
  { suggest: "Smart Band Saw", jmlDicari: 21 },
  { suggest: "Smart Table Saw", jmlDicari: 21 },
  { suggest: "Smart Miter Saw", jmlDicari: 21 },
  { suggest: "Smart Jointer", jmlDicari: 21 },
  { suggest: "Smart Planer", jmlDicari: 21 },
  { suggest: "Smart Router", jmlDicari: 21 },
  { suggest: "Smart Sander", jmlDicari: 21 },
  { suggest: "Smart Drill Press", jmlDicari: 21 },
  { suggest: "Smart Dust Collector", jmlDicari: 21 },
  { suggest: "Smart Air Filtration System", jmlDicari: 21 },
  { suggest: "Smart Welding Machine", jmlDicari: 21 },
  { suggest: "Smart Plasma Cutter", jmlDicari: 21 },
  { suggest: "Smart Oxy-Fuel Cutting Torch", jmlDicari: 21 },
  { suggest: "Smart Metalworking Tools", jmlDicari: 21 },
  { suggest: "Smart Blacksmithing Tools", jmlDicari: 21 },
  { suggest: "Smart Locksmithing Tools", jmlDicari: 21 },
  { suggest: "Smart Engraving Tools", jmlDicari: 21 },
  { suggest: "Smart Jewelry Making Tools", jmlDicari: 21 },
  { suggest: "Smart Lapidary Tools", jmlDicari: 21 },
  { suggest: "Smart Stained Glass Tools", jmlDicari: 21 },
  { suggest: "Smart Mosaic Tools", jmlDicari: 21 },
  { suggest: "Smart Leatherworking Tools", jmlDicari: 21 },
  { suggest: "Smart Bookbinding Tools", jmlDicari: 21 },
  { suggest: "Smart Papermaking Tools", jmlDicari: 21 },
  { suggest: "Smart Calligraphy Tools", jmlDicari: 21 },
  { suggest: "Smart Stamp Making Tools", jmlDicari: 21 },
  { suggest: "Smart Silk Screen Printing Tools", jmlDicari: 21 },
  { suggest: "Smart Lino Printing Tools", jmlDicari: 21 },
  { suggest: "Smart Etching Tools", jmlDicari: 21 },
  { suggest: "Smart Letterpress Tools", jmlDicari: 21 },
  { suggest: "Smart Foil Stamping Tools", jmlDicari: 21 },
  { suggest: "Smart Die Cutting Tools", jmlDicari: 21 },
  { suggest: "Smart Embossing Tools", jmlDicari: 21 },
  { suggest: "Smart Quilling Tools", jmlDicari: 21 },
  { suggest: "Smart Scrapbooking Tools", jmlDicari: 21 },
  { suggest: "Smart Card Making Tools", jmlDicari: 21 },
  { suggest: "Smart Origami Tools", jmlDicari: 21 },
  { suggest: "Smart Papercrafting Tools", jmlDicari: 21 },
  { suggest: "Smart Drawing Tools", jmlDicari: 21 },
  { suggest: "Smart Painting Tools", jmlDicari: 21 },
  { suggest: "Smart Sculpting Tools", jmlDicari: 21 },
  { suggest: "Smart Printmaking Tools", jmlDicari: 21 },
  { suggest: "Smart Darkroom Tools", jmlDicari: 21 },
  { suggest: "Smart Photo Editing Software", jmlDicari: 21 },
  { suggest: "Smart Video Editing Software", jmlDicari: 21 },
  { suggest: "Smart Audio Editing Software", jmlDicari: 21 },
  { suggest: "Smart 3D Modeling Software", jmlDicari: 21 },
  { suggest: "Smart Animation Software", jmlDicari: 21 },
  { suggest: "Smart Game Development Software", jmlDicari: 21 },
  { suggest: "Smart Graphic Design Software", jmlDicari: 21 },
  { suggest: "Smart Web Design Software", jmlDicari: 21 },
  { suggest: "Smart App Development Software", jmlDicari: 21 },
  { suggest: "Smart Programming Software", jmlDicari: 21 },
  { suggest: "Smart Coding Software", jmlDicari: 21 },
  { suggest: "Smart Database Management Software", jmlDicari: 21 },
  { suggest: "Smart Project Management Software", jmlDicari: 21 },
  { suggest: "Smart Office Suite Software", jmlDicari: 21 },
  { suggest: "Smart Accounting Software", jmlDicari: 21 },
  { suggest: "Smart CRM Software", jmlDicari: 21 },
  { suggest: "Smart ERP Software", jmlDicari: 21 },
  { suggest: "Smart Virtualization Software", jmlDicari: 21 },
  { suggest: "Smart Backup Software", jmlDicari: 21 },
  { suggest: "Smart Security Software", jmlDicari: 21 },
];

// searchSuggest
//   .insertMany(dummyData)
//   .then(() => {
//     console.log("Dummy data inserted successfully!");
//     mongoose.connection.close();
//   })
//   .catch((error) => {
//     console.error("Error inserting dummy data: ", error);
//     mongoose.connection.close();
//   });
